# Build and deploy the site to GitHub Pages.

name: Deploy the site to GitHub Pages.

# Run whenever the `website/public` folder in the `main` branch changes.
on:
  push:
    branches:
      - "main"
    paths:
      - "public/**"
  # Allow manual runs from the Actions tab
  workflow_dispatch:

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v3
      - name: Deploy site
        run: git push origin `git subtree split --prefix public main`:gh-pages --force
